name: Update Blog Posts Only
on:
  schedule:
    # 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 파이썬 스크립트 실행 부분은 제거했습니다 (충돌 방지)

      - name: Update README with Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://v2.velog.io/rss/bluepaper14"
          max_post_count: 3
