name: Update Blog Posts
on:
  schedule:
    # 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          # 여기가 핵심입니다 (아이디 변경됨)
          feed_list: "https://v2.velog.io/rss/bluepaper02"
          max_post_count: 3
